FROM python:3.10-slim-buster

WORKDIR /backend-flask
# go outside contianer and copy this files to ==> this container
#this contain the libraries want to install to run the app
COPY requirements.txt requirements.txt

#inside this container 
#install the python library used for the app 
RUN pip3 install -r requirements.txt

# outside container ==> inside container
# (.) means everything in the current directory 
#firs period (.) /backend-flask  (outside container)
# second period (.) /backend-flask(inside the container)
COPY . .
# set environment  variables (env vars)
# inside container and will remain set when the container is running
ENV FLASK_ENV=development

EXPOSE ${PORT}
# python3 -m flask run --host=0.0.0.0 --port=4567
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567"]